### ISSUE TITLE
power9 arch

### ISSUE THREAD

**Issue by dsschult** [icecube/photospline#15]
We have an allocation on Summit, a power9 machine.  photospline doesn't build there.  First error is:
```
  >> 194    /autofs/nccs-svm1_proj/ast165/cvmfs/icecube.opensciencegrid.org/py3
            -v4.1.0/RHEL_7_ppc64le/spack/var/spack/stage/photospline-2.0.4-ekyf
            ea5cdkamk35ll2psqhhxhy4yqcvo/photospline-2.0.4/include/photospline/
            detail/simd.h:33:27: error: cannot convert '__vector(4) int' to 'v4
            sf' {aka '__vector(4) float'} in assignment
```
There are no special simd instructions, as far as I'm aware.

**Comment by cnweaver** [comment]
Interesting; this may take a little digging to figure out what's needed to get this working. What does `CMAKE_SYSTEM_PROCESSOR` end up being on such a system? We request use of Altivec if it's `powerpc`/`ppc`, but I imagine that doesn't match in this case.

**Comment by dsschult** [comment]
`CMAKE_SYSTEM_PROCESSOR` is `ppc64le`

Nathan seems to have access to a power9 system, and is looking into this.

**Comment by cnweaver** [comment]
Definitely happy to let him identify a fix then.
