### ISSUE TITLE
requires python 3.10

### ISSUE THREAD

**Issue by The-Ludwig** [icecube/photospline#29]
L191 in `CMakeLists.txt` requires python 3.10 (`get_preffered_scheme`), which is not listed in the dependencies. 
 
https://github.com/icecube/photospline/blob/233a5d71dca9e047f4daace4792ccb5797b90793/CMakeLists.txt#L192

**Comment by cnweaver** [comment]
Sorry about that, https://github.com/icecube/photospline/commit/682bf1e87192b85d3ce921cc2f308be3b797752d should restore compatibility with 2.7-3.9.

**Comment by cnweaver** [comment]
Closing as this seems to be dealt with.

**Comment by cnweaver** [comment]
Closing as this seems to be dealt with.
